# Generated by Django 3.2.13 on 2023-01-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default='Yummy and Delicious meals. place your order and it will be delivered at your door step'),
        ),
    ]
