# Generated by Django 3.2.13 on 2023-01-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_shop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('package', models.CharField(max_length=277)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=257)),
                ('num_of_packs', models.IntegerField()),
                ('contact', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('user_preference', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
