# Generated by Django 3.2.13 on 2023-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='num_of_packs',
            field=models.CharField(max_length=255),
        ),
    ]
