# Generated by Django 3.2.13 on 2023-01-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_services_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_shop',
            field=models.CharField(default='Testing Service', max_length=289),
        ),
    ]
